# Generated by Django 4.1.4 on 2022-12-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_tickets_id_acciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='celular',
            field=models.CharField(default='Sin celular', max_length=15),
        ),
        migrations.AddField(
            model_name='acciones',
            name='correo',
            field=models.CharField(default='Sin correo', max_length=100),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=200),
        ),
    ]
