# Generated by Django 4.1.4 on 2022-12-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_accion', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('activa', models.BinaryField(default=True)),
            ],
        ),
    ]
